theme: jekyll-theme-minimal

title: Akkupack-NG
description: A AKKU-Pack gas gauge
logo: https://github.com/eurovibes/akkupack-ng/raw/master/images/logo.png
show_downloads: true

github:
  zip_url: downloads/fabrication.zip
  tar_url: downloads/fabrication.tar.gz
